version: "3"

vars:
  IMAGE_NAME: idan006/idanhub
  TAG: local
  CLUSTER_NAME: idan-app
  NAMESPACE: idan-app
  RELEASE_NAME: idan-app
  SERVICE_NAME: idan-app
  LOCAL_PORT: 8080
  SERVICE_PORT: 80

tasks:
  deploy:
    desc: Deploy app to kind and start port-forward
    silent: true
    cmds:
      # Ensure kind cluster exists
      - kind get clusters | grep -q "^{{.CLUSTER_NAME}}$" || kind create cluster --name {{.CLUSTER_NAME}}

      # Load image into kind
      - kind load docker-image {{.IMAGE_NAME}}:{{.TAG}} --name {{.CLUSTER_NAME}}

      # Deploy via Helm (NO heredoc, NO shell block)
      - helm upgrade --install {{.SERVICE_NAME}} helm/my-app --namespace {{.NAMESPACE}} --create-namespace --set image.tag={{.TAG}}

      # Start port-forward in background
      - pgrep -f "kubectl port-forward svc/{{.SERVICE_NAME}}" >/dev/null || nohup kubectl port-forward svc/{{.SERVICE_NAME}} {{.LOCAL_PORT}}:{{.SERVICE_PORT}} -n {{.NAMESPACE}} >/tmp/{{.SERVICE_NAME}}-port-forward.log 2>&1 &


  status:
    desc: Show Kubernetes deployment status
    cmds:
      - kubectl get pods -n {{.NAMESPACE}}
      - kubectl get svc -n {{.NAMESPACE}}

  verify:
    desc: Verify all application endpoints via port-forward
    silent: true
    cmds:
      - |
        set -e

        echo "🔍 Verifying application endpoints..."

        curl -sf http://localhost:8080/my-app | grep -q "Hello, World!" \
          && echo "✔ /my-app OK" \
          || (echo "✖ /my-app FAILED" && exit 1)

        curl -sf http://localhost:8080/about | grep -q "This is a sample Node.js application for Kubernetes deployment testing." \
          && echo "✔ /about OK" \
          || (echo "✖ /about FAILED" && exit 1)

        curl -sf http://localhost:8080/ready | grep -q "Ready" \
          && echo "✔ /ready OK" \
          || (echo "✖ /ready FAILED" && exit 1)

        curl -sf http://localhost:8080/live | grep -q "Alive" \
          && echo "✔ /live OK" \
          || (echo "✖ /live FAILED" && exit 1)

        curl -sf http://localhost:8080/classified | grep -q "You should not be here!!!" \
          && echo "✔ /classified OK" \
          || (echo "✖ /classified FAILED" && exit 1)

        curl -sf http://localhost:8080/metrics | grep -E -q "^[a-zA-Z_:][a-zA-Z0-9_:]*" \
          && echo "✔ /metrics OK (Prometheus-style output detected)" \
          || (echo "✖ /metrics FAILED" && exit 1)

        echo "✅ All verification checks passed"

  cleanup:
    desc: Remove application and kind cluster
    silent: true
    cmds:
      - |
        echo "🧹 Cleaning up Helm release and namespace"
        helm uninstall {{.SERVICE_NAME}} -n {{.NAMESPACE}} || true
        kubectl delete namespace {{.NAMESPACE}} --ignore-not-found

      - |
        echo "🧹 Deleting kind cluster '{{.CLUSTER_NAME}}'"
        kind delete cluster --name {{.CLUSTER_NAME}} || true

      - |
        echo "🧹 Stopping port-forward if running"
        pkill -f "kubectl port-forward svc/{{.SERVICE_NAME}}" || true

      - echo "✔ Cleanup completed"


